set year=2009
set major=1
set minor=11
set step=0
set PREVPRODUCTVERSION=1.10
set RELEASE=%major%.%minor%.%step%
set BRCC=C:\Program Files\CodeGear\RAD Studio\5.0
set QRXI=C:\Program Files\QuickReportsXI
set hc32=c:\Progra~1\Borland\Delphi7\help\tools\hcw
set hhc=C:\Program Files\HTML Help Workshop\hhc
